### ISSUE TITLE
In docker images, what is the corresponding path of the loaded `application.properties` ?

### ISSUE THREAD

**Issue by linghengqian** [apache/dubbo-admin#845] opened 2021-11-15 06:10 UTC
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

In docker images, what is the corresponding path of the loaded `application.properties` ?
I did not see instructions like this in the documentation page. ( https://hub.docker.com/r/apache/dubbo-admin )

**Comment by KeRan213539** [comment] 2021-11-15 09:22
#825

**Comment by KeRan213539** [comment] 2021-11-15 09:26
Duplicate of #825

**Comment by linghengqian** [comment] 2021-11-15 13:50
> Duplicate of #825

Maybe what I expressed is not accurate enough. According to the meaning of https://github.com/apache/dubbo-admin/blob/develop/docker/stack.yml, can I understand that `application.properties` cannot pass `volumes` mounting into `container`, can only be configured by `environment`?

**Comment by linghengqian** [comment] 2021-11-16 08:20
> > > Duplicate of #825
> > 
> > 
> > Maybe what I expressed is not accurate enough. According to the meaning of https://github.com/apache/dubbo-admin/blob/develop/docker/stack.yml, can I understand that `application.properties` cannot pass `volumes` mounting into `container`, can only be configured by `environment`?
> 
> Both application.properties and environment will be loaded into the spring container. Environment has higher priority than application.properties. If you want to modify the configuration by modifying application.properties, you can only package the docker image yourself

Thank you for your answer.

**Closed** 2021-11-16 08:20 UTC
